### ISSUE TITLE
Small issues

### ISSUE THREAD

**Issue by Bouncner** [Bensk1/example-plugin#1]
Unloading and reloading crashes:
```
(debug)> unload_plugin deb/libCompressionDriver.dylib
Plugin (deb/libCompressionDriver.dylib) stopped.
(debug)> load_plugin deb/libCompressionDriver.dylib
libc++abi.dylib: terminating with uncaught exception of type std::logic_error: /Users/martin/Programming/HyrisePluginning/hyrise/src/lib/utils/plugin_manager.cpp:35 Loading plugin failed: A plugin with name  CompressionDriver already exists.
[1]    46557 abort      ./deb/hyriseConsole
```

Further, the README says that `load_plugin` takes a name and a path. At least with the current Hyrise master, we only take a path.

**Comment by Bensk1** [comment]
Thanks for bringing this up! I fixed the README and will push it later together with a new version of the Hyrise submodule. Unloading and reloading works on my machine. Could you try: `unload_plugin CompressionDriver`?

Do you think I should clarify the help message of the console? It currently says:

```
load_plugin FILE      - Load and start plugin stored at FILE
unload_plugin NAME    - Stop and unload the plugin libNAME.so/dylib (also clears the query cache)
```

**Comment by Bensk1** [comment]
However, this message `Plugin (deb/libCompressionDriver.dylib) stopped.` is wrong.

**Comment by Bensk1** [comment]
Should be fixed now. Could you confirm @Bouncner?

**Comment by Bouncner** [comment]
```
(debug)> load_plugin deb/libCompressionDriver.dylib
ddddddiiiasdfdskjf;daslfj
Plugin (CompressionDriver) successfully loaded.
(debug)> unload_plugin deb/libCompressionDriver.dylib
Plugin (deb/libCompressionDriver.dylib) stopped.
(debug)> load_plugin deb/libCompressionDriver.dylib
libc++abi.dylib: terminating with uncaught exception of type std::logic_error: /Users/martin/Programming/HyrisePluginning/hyrise/src/lib/utils/plugin_manager.cpp:35 Loading plugin failed: A plugin with name  CompressionDriver already exists.
[1]    49713 abort      ./deb/hyriseConsole
➜  HyrisePluginning git:(master) ✗
```

So I misread the help on purpose and unloading still appeared to work but reloading crashed.

When unloading using the name (which is kind of strange, but ok for me), reloading works fine. So let the console crash when providing the file instead of the name?

**Comment by Bensk1** [comment]
I don't know how you are doing this. Are you sure that you have the recent hyrise master?
```
(debug)> load_plugin cmake-build-debug/libExamplePlugin.dylib
Plugin (ExamplePlugin) successfully loaded.
(debug)> unload_plugin ExamplePlugin
Plugin (ExamplePlugin) stopped.
(debug)> load_plugin cmake-build-debug/libExamplePlugin.dylib
Plugin (ExamplePlugin) successfully loaded.
(debug)> unload_plugin cmake-build-debug/libExamplePlugin.dylib
libc++abi.dylib: terminating with uncaught exception of type std::logic_error: src/lib/utils/plugin_manager.cpp:54 Unloading plugin failed: A plugin with name  cmake-build-debug/libExamplePlugin.dylib does not exist.
[1]    19812 abort      ./cmake-build-debug/hyriseConsole
```

> So let the console crash when providing the file instead of the name?

That's exactly what the new master does.


> When unloading using the name (which is kind of strange, but ok for me)

That was discussed before merging the PluginManager in the first place in the main repo.


I will update this repo now.

**Comment by Bouncner** [comment]
Hyrise was at 1edf561f4. I'll do a complete rebuild to ensure I don't have any leichen in the cache keller.

**Comment by Bouncner** [comment]
Yep, I guess I was on an old hyrise. Crashes with `unload_plugin` file.

**Comment by Bensk1** [comment]
Perfect, thanks!
